# For all options for RStudio images, see https://rocker-project.org/images/versioned/rstudio.html
FROM rocker/rstudio

RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install -y ssh nano less curl python3 python3-pip python3-venv python3-virtualenv
RUN apt-get install -y libpng-dev libglpk-dev libxt-dev liblzma-dev libbz2-dev

USER rstudio

RUN R -e "install.packages('synapser', repos = c('http://ran.synapse.org', 'http://cran.fhcrc.org'))"

USER root
